# Site settings
title: Lloyd Torres
description: >
  Lloyd Torres is a Computer Engineering graduate from the University of Waterloo.
baseurl: "" # subpath
url: "http://lloydtorres.com"
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
- jekyll-redirect-from
- jekyll-sitemap
