# Site settings
title: Lloyd Torres
description: > 
  Lloyd Torres is an Electrical Engineering co-op student at the University of Waterloo.
baseurl: "" # subpath
url: "http://lloydtorres.com"
timezone: Canada/Eastern

# Build settings
markdown: kramdown
highlighter: pygments

gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap

jekyll-mentions: https://twitter.com
tag_dir: /log/tag