# Site settings
title: Lloyd Torres
description: > 
  Lloyd Torres is a Computer Engineering co-op student at the University of Waterloo.
baseurl: "" # subpath
url: "http://lloydtorres.com"
timezone: Canada/Eastern

# Build settings
markdown: kramdown
highlighter: pygments

gems:
- jekyll-redirect-from
- jekyll-sitemap

tag_dir: /log/tag